### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by nader8** [fireinrain/opaitokens#2]
=== RUN   TestUserCase
use fakeopen proxy for auth failed: error getting access token: 429 Too Many Requeststoken info: &{abcd@gmail.com pass{    0 } {   0 } true}

**Comment by fireinrain** [comment]
openai 登录加了arkos，很难过

**Comment by nader8** [comment]
:( 有没有解决办法？

**Comment by zwluoqi** [comment]
预计能解决吗

**Comment by fireinrain** [comment]
> 预计能解决吗

fakeopen那边要是重新放出登录接口 我这边可以及时同步  我在fakeopen那个tg群

**Comment by fireinrain** [comment]
> 预计能解决吗

新版本支持使用openai 官方的refresh token来获得新的accessToken了，参考文档中的以withRefreshToken的方法即可

**Comment by fireinrain** [comment]
好消息 今天下午zhile大佬更新了，目前可以用普通的账号密码方式登录获取了。
使用方法没有变，这个issue 我就先关了哦
